spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 808799
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true