spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 808799
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
# 控制返回字段，若为空则不反回
  jackson:
    default-property-inclusion: non_null
  redis:
    host: xxx
    port: 6379
    password:
server:
  context-path: /sell

wechat:
  mpAppId:
  mpAppSecret:
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  KeyPath:
  templateId:
    orderStatus:

projectUrl:
  wechatMpAuthorize:
  wechatOpenAuthorize:
  sell:
